export const ActionTypes = {
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  CREATE_EVENT: "CREATE_EVENT",
  SET_ALL_EVENTS: "SET_ALL_EVENTS",
  SET_ACTUAL_POSITION: "SET_ACTUAL_POSITION",
  SET_CURRENT_USER: "SET_CURRENT_USER",
};
